### ISSUE TITLE
Provide an endpoint, for Rivet, to restart devnet in forking mode

### ISSUE THREAD

**Issue by ivpavici** [0xSpaceShard/starknet-devnet-rs#616] opened 2024-09-25 12:13 UTC
We would like to fork devnet from Starknet Rivet.

The idea is to send an RPC request to devnet, with an URL and optional block number, so that the devnet gets restarted - forked from this URL (and optional block)!

**Comment by estherbreath** [comment] 2024-09-27 12:57
Hi @ivpavici 
I am a Smart contract and a fullstack developer.
Could you kindly assign me to work on this issue, please?

**Comment by FabijanC** [comment] 2024-12-09 13:00
Duplicate of #504

**Closed by FabijanC** 2024-12-09 13:00 UTC
Labels: enhancement
